ALTER TABLE user_profile DROP CONSTRAINT fk_users;
ALTER TABLE workspace DROP CONSTRAINT fk_users;
ALTER TABLE workspace_users DROP CONSTRAINT fk_users;
ALTER TABLE workspace_users DROP CONSTRAINT fk_workspace;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS workspace;
DROP TABLE IF EXISTS workspace_users;
DROP TABLE IF EXISTS blacklisted_access_tokens;
DROP TABLE IF EXISTS invites;
DROP TABLE IF EXISTS email_verification;