ALTER TABLE user_profile DROP CONSTRAINT fk_users;
ALTER TABLE workspace DROP CONSTRAINT fk_users;
ALTER TABLE workspace_users DROP CONSTRAINT fk_users;
ALTER TABLE workspace_users DROP CONSTRAINT fk_workspace;
DROP TABLE IF EXISTS email_verification;
DROP TABLE IF EXISTS login_magic_code;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS employer;
DROP TABLE IF EXISTS freelancer;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS workspace;
DROP TABLE IF EXISTS workspace_users;
DROP TABLE IF EXISTS token_pair;
DROP TABLE IF EXISTS invites;
DROP TABLE IF EXISTS email_verification;