// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Dashboard struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Name      string         `json:"name"`
	Logo      sql.NullString `json:"logo"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Status    string         `json:"status"`
	PlanID    uuid.UUID      `json:"plan_id"`
}

type DashboardMember struct {
	ID                 int32        `json:"id"`
	MemberID           int32        `json:"member_id"`
	DashboardID        int32        `json:"dashboard_id"`
	AccessLevel        uuid.UUID    `json:"access_level"`
	InvitedBy          int32        `json:"invited_by"`
	InvitedAt          time.Time    `json:"invited_at"`
	AcceptedInvitation sql.NullBool `json:"accepted_invitation"`
	JoinedAt           time.Time    `json:"joined_at"`
}

type DashboardRole struct {
	ID       uuid.UUID `json:"id"`
	RoleName string    `json:"role_name"`
}

type EmailUpdateVerificationCode struct {
	ID           uuid.UUID `json:"id"`
	UserID       int32     `json:"user_id"`
	Code         string    `json:"code"`
	EmailAddress string    `json:"email_address"`
	Expiry       time.Time `json:"expiry"`
}

type Invite struct {
	ID                  uuid.UUID     `json:"id"`
	InviteFrom          int32         `json:"invite_from"`
	StudentEmailAddress string        `json:"student_email_address"`
	InvitationCode      string        `json:"invitation_code"`
	DashboardID         sql.NullInt32 `json:"dashboard_id"`
	AccessLevel         string        `json:"access_level"`
	InviteExpiry        time.Time     `json:"invite_expiry"`
}

type LoginMagicCode struct {
	ID           uuid.UUID `json:"id"`
	UserID       int32     `json:"user_id"`
	Code         string    `json:"code"`
	EmailAddress string    `json:"email_address"`
	CodeExpiry   time.Time `json:"code_expiry"`
}

type Plan struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type SignupEmailVerificationCode struct {
	ID               uuid.UUID `json:"id"`
	EmailAddress     string    `json:"email_address"`
	VerificationCode string    `json:"verification_code"`
	Expiry           time.Time `json:"expiry"`
}

type User struct {
	ID            int32     `json:"id"`
	FullName      string    `json:"full_name"`
	EmailAddress  string    `json:"email_address"`
	ClientOs      string    `json:"client_os"`
	ClientAgent   string    `json:"client_agent"`
	ClientBrowser string    `json:"client_browser"`
	Timezone      string    `json:"timezone"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserProfile struct {
	UserID int32 `json:"user_id"`
}

type UserSession struct {
	ID           uuid.UUID `json:"id"`
	UserID       int32     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	ClientAgent  string    `json:"client_agent"`
	ClientIp     string    `json:"client_ip"`
	ClientOs     string    `json:"client_os"`
	Active       bool      `json:"active"`
	IssuedAt     time.Time `json:"issued_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}
