// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Dashboard struct {
	UserID       int32          `json:"user_id"`
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	ProfileImage sql.NullString `json:"profile_image"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Status       string         `json:"status"`
	Tier         string         `json:"tier"`
}

type DashboardMember struct {
	UserID      int32     `json:"user_id"`
	DashboardID int32     `json:"dashboard_id"`
	AccessLevel string    `json:"access_level"`
	JoinedOn    time.Time `json:"joined_on"`
}

type EmailVerification struct {
	EmailAddress              string    `json:"email_address"`
	VerificationCode          string    `json:"verification_code"`
	VerificationCodeExpiresAt time.Time `json:"verification_code_expires_at"`
}

type Invite struct {
	EmailAddress   string        `json:"email_address"`
	InvitationCode string        `json:"invitation_code"`
	WorkspaceID    sql.NullInt32 `json:"workspace_id"`
	AccessLevel    string        `json:"access_level"`
}

type LoginMagicCode struct {
	UserID       int32     `json:"user_id"`
	Code         string    `json:"code"`
	EmailAddress string    `json:"email_address"`
	CodeExpiry   time.Time `json:"code_expiry"`
}

type User struct {
	ID           int32     `json:"id"`
	FullName     string    `json:"full_name"`
	EmailAddress string    `json:"email_address"`
	Password     string    `json:"password"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserProfile struct {
	UserID int32 `json:"user_id"`
}

type UserSession struct {
	ID           uuid.UUID `json:"id"`
	UserID       int32     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	ClientAgent  string    `json:"client_agent"`
	ClientIp     string    `json:"client_ip"`
	ClientOs     string    `json:"client_os"`
	Active       bool      `json:"active"`
	IssuedAt     time.Time `json:"issued_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}
