// Code generated by sqlc. DO NOT EDIT.
// source: token_pair.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTokenPair = `-- name: CreateTokenPair :one
INSERT INTO token_pair(user_id, access_token_id, refresh_token_id)
VALUES ($1, $2, $3)
RETURNING user_id, access_token_id, refresh_token_id
`

type CreateTokenPairParams struct {
	UserID         int32     `json:"user_id"`
	AccessTokenID  uuid.UUID `json:"access_token_id"`
	RefreshTokenID uuid.UUID `json:"refresh_token_id"`
}

func (q *Queries) CreateTokenPair(ctx context.Context, arg CreateTokenPairParams) (TokenPair, error) {
	row := q.db.QueryRowContext(ctx, createTokenPair, arg.UserID, arg.AccessTokenID, arg.RefreshTokenID)
	var i TokenPair
	err := row.Scan(&i.UserID, &i.AccessTokenID, &i.RefreshTokenID)
	return i, err
}
