// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id)
VALUES ($1)
RETURNING id, full_name, email_address, client_os, client_agent, client_browser, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.EmailAddress,
		&i.ClientOs,
		&i.ClientAgent,
		&i.ClientBrowser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
