// Code generated by sqlc. DO NOT EDIT.
// source: workspace.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspace (user_id, name)
VALUES ($1, $2)
RETURNING user_id, id, name, profile_image, created_at, updated_at, status, tier
`

type CreateWorkspaceParams struct {
	UserID sql.NullInt32 `json:"user_id"`
	Name   string        `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.UserID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Name,
		&i.ProfileImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Tier,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspace
SET name = $2
WHERE id = $1
RETURNING user_id, id, name, profile_image, created_at, updated_at, status, tier
`

type UpdateWorkspaceParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Name,
		&i.ProfileImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Tier,
	)
	return i, err
}
